repos:

  #- repo: https://github.com/pycqa/flake8
  #  rev: 7.3.0
  #  hooks:
  #    - id: flake8
  #      args: ['--max-line-length=180']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    - id: ruff
      args: ["--fix", "--line-length=180", "--select=E,F,I,UP,B,SIM,C4,PL", "--ignore=E501"]
      exclude: ^examples/, ^tests/
      files: \.py$
    - id: ruff-format
      args: ["--line-length=180"]
      exclude: ^examples/, ^tests/
      files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    - id: mypy
      additional_dependencies:
        - hypothesis>=6.97.0

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        additional_dependencies:
          - pytest
          - hypothesis>=6.97.0
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
      exclude: ^examples/
    - id: trailing-whitespace
      exclude: ^examples/
    - id: check-yaml
